const actionTypes = {
  UPDATE_POINT: 'UPDATE_POINT',
  BECOME_ACTOR: 'BECOME_ACTOR',
  BECOME_GUESSER: 'BECOME_GUESSER',
  BECOME_SPECTATOR: 'BECOME_SPECTATOR',
  UPDATE_GAME_CONTENT: 'UPDATE_GAME_CONTENT',
  UPDATE_GAME_TYPE: 'UPDATE_GAME_TYPE',
  UPDATE_WORD_LIST: 'UPDATE_WORD_LIST',
  UPDATE_READY_ROOM: 'UPDATE_READY_ROOM',
  UPDATE_READY_WORD: 'UPDATE_READY_WORD',
  UPDATE_GAME_WORD: 'UPDATE_GAME_WORD',
  UPDATE_GAME_TIME: 'UPDATE_GAME_TIME',
  UPDATE_WORD_COUNT: 'UPDATE_WORD_COUNT',
  OVERRIDE_GAME: 'OVERRIDE_GAME',
}

export default actionTypes;