const actionTypes = {
  UPDATE_POINT: 'UPDATE_POINT',
  BECOME_ACTOR: 'BECOME_ACTOR',
  BECOME_GUESSER: 'BECOME_GUESSER',
  BECOME_SPECTATOR: 'BECOME_SPECTATOR',
  UPDATE_GAME_CONTENT: 'UPDATE_GAME_CONTENT',
  UPDATE_GAME_TYPE: 'UPDATE_GAME_TYPE'

}

export default actionTypes;