const actionTypes = {
  UPDATE_PAGE: 'UPDATE_PAGE',
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  LOAD_PROGRESS: 'LOAD_PROGRESS',
  RESET_LOAD: 'RESET_LOAD',
  TOGGLE_SERVER: 'TOGGLE_SERVER',
  SET_FEATURE_TOGGLE: 'SET_FEATURE_TOGGLE',
}

export default actionTypes;